wip: sequelize boilerplate for votes
platf0rm/platform-api pull request #8
Opened 2017-03-26 06:01 UTC by kimerran

let's discuss these sample codes. some directories made by Sequelize.

2017-03-26 09:16 UTC, ghost requested changes
Please make sure that every `.js` files are in strict mode.

2017-03-26 09:28 UTC, ghost approved these changes

2017-03-26 10:26 UTC, ac-opensource requested changes

2017-03-26 10:26 UTC, ac-opensource commented on controllers/vote_controller.js
> +      });
No error handling?

2017-03-26 19:20 UTC, TheoryOfNekomata reviewed
Consider using ES6 features for `models/index.js`.

With that said, ESLint with ecmaVersion: 2017 should be used.

2017-03-27 00:31 UTC, kimerran commented
@Temoto-kun can you specify which lines needed to be in ES6. And the reason why the need for ES2017? thanks

2017-03-27 01:57 UTC, Temoto-kun commented
The whole file is in ES5. Compare with other files in the folder. Anyway, it's not much of a showstopper.

2017-03-27 02:56 UTC, ac-opensource approved these changes

2017-03-27 03:01 UTC, merged